#!/usr/bin/env python3
from serial_communication.serial_utils import connect_arduino
from utils import wait

arduino = connect_arduino(protection=True, port_selection=False)
wait(1)
arduino.write(b'a')

