
def show_instructions():
    print("Available commands:")
    print('exit - exit the program')
    print('A - Connect to Arduino')
    print('a - Disconnect from Arduino')
    print('G# - move servo to angle # (angle between 30 and 150)')
    print('C# - move motors at speed # (speed between -100 and 100)')
    print('c## - move motor # at speed # (speed between -100 and 100, motor between 1 and 2)')
    print('D# - move motors at speed # (speed between -100 and 100) (Progressive)')
    print('d## - move motor # at speed # (speed between -100 and 100, motor between 1 and 2) (Progressive)')
    print('N - get encoder values')
    print('T - get motor voltages')
    print('F# - move forward for # seconds')
    print('B# - move backward for # seconds')
    print('L# - turn left for # seconds')
    print('R# - turn right for # seconds')
    print('I# - set protection # (0 to disable, 1 to enable)')
    print('repeat <commands> - repeat the commands indefinitely until "s" is typed')
